CREATE TABLE IF NOT EXISTS students
(
    id     bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name   varchar(255) NOT NULL,
    age    int          NOT NULL,
    rating int          NOT NULL,
    PRIMARY KEY (id)
);

SELECT *
FROM students;

INSERT INTO students(id, name, age, rating)
VALUES (1, 'Vagif', 19, 10);